name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Start Login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build the Docker image
      run: |
         docker build -t lookandcris/private-lookandcris:0.0.1 .
         docker build -t lookandcris/private-lookandcris:latest .
    - name: Push the Docker image
      run: | 
         docker push lookandcris/private-lookandcris:0.0.1
         docker push lookandcris/private-lookandcris:latest
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
